name: Run CPU Pytests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  run-cpu-pytests:
    name: Run CPU Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install -r toto/requirements.txt

    - name: Run CPU-specific Pytests
      run: pytest toto/test -m "not cuda"

  run-mypy:
    name: Run Type Checking
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install -r toto/requirements.txt

    - name: Run MyPy
      run: mypy toto --config-file mypy.ini --check-untyped-defs

  run-black:
    name: Run Code Formatting Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install -r toto/requirements.txt

    - name: Run Black
      run: black toto --check
