name: Run CPU Pytests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  run-cpu-pytests:
    name: Run CPU Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install -r toto/requirements.txt

    - name: Run CPU-specific Pytests
      run: pytest toto/test -m "not cuda"
