name: Run CUDA Pytests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  run-cuda-pytests:
    name: Run CUDA Tests
    runs-on: APM-4-CORE-GPU-LINUX
    steps:
    - name: Checkout Code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: pip install -r toto/requirements.txt

    - name: Verify GPU Availability
      run: |
        python -c "import torch; assert torch.cuda.is_available(), 'CUDA GPU not available'"

    - name: Run CUDA-specific Pytests
      run: pytest toto/test -m cuda
